### ISSUE TITLE
Support for namespaced models

### ISSUE THREAD

**Issue by adamhunter** [justbaker/dynomite#2]
Currently namespaced models generate table names with a `/` in them.  For example `Foo::Bar` becomes `foo/bar` which is not a valid dynamo table name as far as I can tell.

**Comment by justbaker** [comment]
@adamhunter: Table names are constrained to `/[a-zA-Z0-9_.-]+/` [AWS Docs on Table name constraints](http://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_CreateTable.html#API_CreateTable_RequestSyntax). I think I'll add an error in migrations to prevent invalid table names, to match the regex. I'll convert `Foo::Bar` to `foo.bar`; my reasoning is naming conversions. `TwoWords::Bar` would become `two_words.bar`.
